### ISSUE TITLE
Open tab in Current Working Directory

### ISSUE THREAD

**Issue by jonnieey** [gryf/tabbedalt#10]
I like this extension but could it be possible to open a new tab from the current working directory instead of $HOME?

**Comment by gryf** [comment]
Well, it's not possible right now. Perhaps because I didn't needed such feature :)

**Comment by jonnieey** [comment]
Thanks. I came across [pgid-cd.pl](https://github.com/mina86/urxvt-tabbedex/blob/master/pgid-cd.pl) which does this. Using it with [urxvt-tabbedex](https://github.com/mina86/urxvt-tabbedex.git) opens it in the current working directory. Hope you will need this feature in the future :)
