### ISSUE TITLE
How to change "Rename tab" shortcut?

### ISSUE THREAD

**Issue by alpiua** [gryf/tabbedalt#11]
Hello.
Thank you for the plagin update.
How i can change "Shift+UP: renaming ?

**Comment by gryf** [comment]
It's hardcoded. You can change it in the code right here:
https://github.com/gryf/tabbed/blob/fb104188a651763bc8d34eb80232cdd452e4ed8d/tabbed#L593
I'm also considering a way for defining shortcuts, although I didn't start it yet.

**Comment by tukusejssirs** [comment]
I hope you could find some time to enable customisation of keyboard shortcuts. I like your extension, but I’d like to change the following shortcuts:
- create new tab: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>;
- close tab: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>W</kbd>;
- rename tab: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>;
- switch to tab by number: <kbd>Alt</kbd>+<kbd>[0-9]</kbd>.

Additional shortcuts for stuff I miss:
- go to next tab (on the right): <kbd>Ctrl</kbd>+<kbd>PgDn</kbd>;
- go to previous tab (on the left): <kbd>Ctrl</kbd>+<kbd>PgUp</kbd>;
- move current tab to the right: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>PgUp</kbd>;
- move current tab to the left: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>PgDn</kbd>.

Thanks for this nice extension! :wink:

**Comment by gryf** [comment]
With the commit bee8e4a you are able to define your own shortcut keys.
