### ISSUE TITLE
commandline installation via curl | sh ?

### ISSUE THREAD

**Issue by rubyFeedback** [gryf/tabbedalt#13]
Hey there,

I found another tabbed extension where a copy/paste line is shown
in the main README. Could this also be done here for tabbedalt?

May simplify installation for people to quickly test it.

**Comment by gryf** [comment]
Hi!

I'm trying to avoid usage of `curl | sh` where there is no need for it. And IMO installation for this plugin is so straightforward as
```bash
$ curl --create-dirs https://raw.githubusercontent.com/gryf/tabbedalt/master/tabbedalt -o ~/.urxvt/ext/tabbedalt
$ urxvt -pe tabbedalt
```
that it doesn't need any special install script which could be passed to the shell. Also note, there are several ways, how urxvt could be invoked to test the script, besides above one, and I don't want to force certain way on anybody.

**Comment by gryf** [comment]
I've added appropriate note in readme.
