### ISSUE TITLE
Geometry setting not honored when using tabs

### ISSUE THREAD

**Issue by weiameili** [gryf/tabbedalt#14]
Hi, the geometry setting in my `.Xresources`, neither the terminal size, nor the positioning, is taken into effect when using this extension. Apparently, this issue persists when using `tabbed` too.

**Comment by gryf** [comment]
That's weird, it works for me - either using X resources, or using the `-geometry` parameter from command line. Perhaps you need to use `xrdb ~/.Xdefaults` after modifying that file?

**Comment by weiameili** [comment]
Edit: the terminal size is set, but it always opens in a corner, instead of the center of the screen, as set in my `.Xresources`

I have run `xrdb` correctly

Perhaps this has something to do with the Package Versions, or the WM. I'm on Deepin 20 (Debian Buster Based) with the default DE, in that case

**Comment by gryf** [comment]
I don't think its a package version fault. As you mentioned, it also happen with tabbed extension, so I guess the reason for not placing terminal in desired place is in a way how enclosing terminal is created. Tabbed extension (so the tabbedalt aswell) create and embed terminal in a "view", window. Perhaps it's an issue within urxvt itself. In other words, there is not much we can do about it from the perl plugin.

**Comment by gryf** [comment]
I think I found the culprit for not preserving window placement. Need to figure out the fix for it.

**Comment by gryf** [comment]
Fixed with d39d1bf0.
