### ISSUE TITLE
Ctrl + / strange behavior 

### ISSUE THREAD

**Issue by ghost** [gryf/tabbedalt#3]
When I press ctrl + / shortcut urxvt falls.
I tried it without tabbed extension and all works.

**Comment by gryf** [comment]
I can confirm, that using tabbed extension for unknown reason using `ctrl-/` will switch to second/third tab.

**Comment by gryf** [comment]
Fixed in commit 41893fbe71b741d38e72293cab4498d3e8aaec51.
