### ISSUE TITLE
TUI in tabs

### ISSUE THREAD

**Issue by y-ates** [gryf/tabbedalt#5]
Running a command with a TUI like `htop` or `s-tui` one can not switch to other buffers anymore as it will show the same result on all tabs (e.g. the output of the program with a TUI). 
Thus, the whole **functionality of tabs is not given anymore** as long as the TUI program is running.

```
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```

**Comment by gryf** [comment]
Hm. I cannot reproduce this behavior. I'm using a lot of tui based apps (`mc`, `htop`, `weechat`, `vim` etc) like daily, and didn't bump on such issue. Maybe there is a problem on your specific urxvt configuration?

**Comment by y-ates** [comment]
This can be closed. Sorry for any inconveniences.
