### ISSUE TITLE
Shift+Down cannot invoke new tab 

### ISSUE THREAD

**Issue by eval-exec** [gryf/tabbedalt#8]

**Comment by eval-exec** [comment]
![2019-07-26_19-33](https://user-images.githubusercontent.com/46400566/61949078-3d711d80-afdc-11e9-92f1-2ff4b3960793.png)

**Comment by eval-exec** [comment]
I can rename tab-name by SHIFT+UP , but cannot invoke new tab by SHIFT+DOWN.
![image](https://user-images.githubusercontent.com/46400566/61949139-642f5400-afdc-11e9-98d7-6d449d0d446e.png)

**Comment by JackieMium** [comment]
same here.
launching urxvt from a terminal and clicking the NEW button and terminal outputed:

```
urxvt: Undefined subroutine &main::-1 called at /home/adam/.urxvt/ext//tabbed line 358.
```

**Comment by gryf** [comment]
Well, yeah. I've changed default tab shortcut to ctrl+shift+n, which is more reasonable for me. Do you want to keep the default from original tabbed?

**Comment by gryf** [comment]
With commit 317f614e8f338f03dac58fbfe6a8b7e820091da1 you'll be able to use "old" shortcut for tab creation. Please, read the README and enjoy.
