### ISSUE TITLE
CTRL+SHIFT

### ISSUE THREAD

**Issue by betcher** [gryf/tabbedalt#9]
How can i change CTRL+SHIFT to another keys?  CTRL+SHIFT is rus/en switch in my OS.

**Comment by gryf** [comment]
Hm. I've missed this question somehow…
ctrl-shift has been chosen arbitrarily because they are close to each other so tha I can spawn desired shell single hand. In other words, its hardcoded, so there is not much choice. What other keys are you considering? ctrl-alt?

**Comment by gryf** [comment]
With the commit bee8e4a you are able to define your own shortcut keys.

**Comment by betcher** [comment]
Thanks
